### ISSUE TITLE
Industry Recognized Certificates 

### ISSUE THREAD

**Issue by pcodesdev** [PanXProject/awesome-certificates#14]
Please consider uploading courses that offer industry Recognized Certificates not just certificates of completion or a badge

**Comment by waleedsadek-panx** [comment]
Totally agree! Would you suggest some?

**Comment by pcodesdev** [comment]
https://www.axelos.com/certifications/propath/prince2-project-management

https://www.pmi.org/certifications/project-management-pmp?s_kwcid=AL!8620!3!457589129416!b!!g!!project%20management%20certification&utm_job_number=5&utm_campaign_name=pmp_lead_generation&utm_region_name=safrica&utm_program_origin=planned_campaign&utm_program_type=continuous_campaign&utm_campaign_intent=acquisition&utm_funnel_stage=lead_acquisition&utm_initiative=certification&utm_product=pmp&utm_marketing_channel=paid_media&utm_marketing_subchannel=search_ppc_nonbranded&utm_start_date=05012015&utm_end_date=12312030&utm_source=google&utm_custom_field_one=pmp_certification_safrica&utm_custom_field_two=pmp_certification_safrica&utm_custom_field_three=457589129416&utm_custom_field_four=project%20management%20certification&utm_custom_field_five=b&gclid=CjwKCAjwrpOiBhBVEiwA_473dCBEJKPPltWAc8gSW94IZs00pQL96NC-ce4iRbhRD_hk3pu_3OH0ZRoCMLEQAvD_BwE

https://www.peoplecert.org/browse-certifications/it-governance-and-service-management/ITIL-1/itil-4-foundation-2565

**Comment by waleedsadek-panx** [comment]
I see what you mean, certifications like ITIL, Comptia+ and such. The thing is, it's almost impossible to find free certifications for these sort of certifications. However I've seen free prep courses, do you think they would be useful to add?

**Comment by waleedsadek-panx** [comment]
For sure! I'll be on the look out. I've found this but I don't think they provide a certificate as well. https://masterofproject.com/p/free-itsm-training
