### ISSUE TITLE
Hi, some filenames have uppercase country codes while others have lowercase. For example, 'job_postings_by_sector_CA.csv' is uppercase but 'provincial_postings_ca.csv' is lowercase. Ensuring consistency across all the filenames would be helpful.

### ISSUE THREAD

**Issue by safwsgithub2** [PanXProject/awesome-certificates#19]
Hi, some filenames have uppercase country codes while others have lowercase. For example, 'job_postings_by_sector_CA.csv' is uppercase but 'provincial_postings_ca.csv' is lowercase. Ensuring consistency across all the filenames would be helpful.

_Originally posted by @pawelgfi in https://github.com/hiring-lab/job_postings_tracker/issues/112_

**Comment by waleedsadek-panx** [comment]
How can I help?

**Comment by waleedsadek-panx** [comment]
I'll close as there is no response. Please feel free to reopen and elaborate.
