### ISSUE TITLE
[BUG] Blockchain Cognitive Class courses not more delivered (I think)

### ISSUE THREAD

**Issue by eapiova** [PanXProject/awesome-certificates#32]
**Describe the bug**
The following Blockchain Cognitive Class courses can't be found by clicking the two links:
- IBM Blockchain Foundation Developer
- Blockchain Essentials

**To Reproduce**
1. Go to Blockchain section
2. Click on one of the first two course links

**Comment by waleedsadek-panx** [comment]
Thanks for pointing it out I'll try to see if they're being offered at a different url or if they stopped offering them completely

**Comment by waleedsadek-panx** [comment]
So these two courses are no longer offered, however I've added [two new courses instead](https://github.com/PanXProject/awesome-certificates#blockchain).
