### ISSUE TITLE
[FEATURE]Android development and cross platform development 

### ISSUE THREAD

**Issue by whoptyyy** [PanXProject/awesome-certificates#42]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by waleedsadek-panx** [comment]
Confirming I got your request! We'll look for Android courses with free certificates and notify you once added!

**Comment by waleedsadek-panx** [comment]
Hello @whoptyyy, I've added two new sections for [Cross-platform](https://github.com/PanXProject/awesome-certificates/tree/main?tab=readme-ov-file#cross-platform-development) and [Native](https://github.com/PanXProject/awesome-certificates/tree/main?tab=readme-ov-file#native-development) and found 9 free certificates, enjoy!
