### ISSUE TITLE
Rhinocam and Illustrator and Photoshop [CERTIFICATE]

### ISSUE THREAD

**Issue by RyukRr07** [PanXProject/awesome-certificates#44]
i am looking for a rhinoceros certificate and rhinocam and illustrator and Photoshop you would help me a lot

**Comment by waleedsadek-panx** [comment]
For sure! will look for them!

**Comment by waleedsadek-panx** [comment]
Hello @RyukRr07, I've updated the list and found some Photoshop and Illustrator courses added [here](https://github.com/PanXProject/awesome-certificates/tree/main?tab=readme-ov-file#design) under design section and for the Rihno I found [this](https://www.mindluster.com/certificate/12429/Rhino-furniture). Hope this helps! If you need any other certificates don't hesitate.
