### ISSUE TITLE
Cloud Computing Basic to Advanced [CERTIFICATE]

### ISSUE THREAD

**Issue by Sumayya-23** [PanXProject/awesome-certificates#45]
I wanted to learn Cloud Computing Basics to Advanced level but the course and the certification isn't available. I request you to please provide it . 
Thank you .

**Comment by waleedsadek-panx** [comment]
Sure thing! Will look for some and add them👍🏾

**Comment by waleedsadek-panx** [comment]
Hello @Sumayya-23, I've added this new section for Cloud Computing, hope it helps with your studies! You can find it [here](https://github.com/PanXProject/awesome-certificates/tree/main?tab=readme-ov-file#cloud-computing). 🚀
