### ISSUE TITLE
I want to add a new certificates to this list

### ISSUE THREAD

**Issue by Dhvijp** [PanXProject/awesome-certificates#47]
Ask us to find free certificates in a specific field that you couldn't find here and we will add it.

**Comment by Dhvijp** [comment]
I want to create a new certificate

**Comment by Dhvijp** [comment]
New certificate

**Comment by waleedsadek-panx** [comment]
Sure thing! In that case you need to:
- Fork this repo 
- Make the edits you want on the 'readme.md' file on your own repo that you just forked
- Once done open a pull request back on PanXProject/awesome-certificates

Let me know if you need help.
