### ISSUE TITLE
JAva

### ISSUE THREAD

**Issue by TejaswiniSeru** [PanXProject/awesome-certificates#61]
Ask us to find free certificates in a specific field that you couldn't find here and we will add it.

**Comment by waleedsadek-panx** [comment]
Hi if you're looking for Java certificates I believe there is beginner one here. https://www.hackerrank.com/skills-verification/java_basic

**Comment by waleedsadek-panx** [comment]
Closing this, let me know if you need to find any other certificates/courses.
